language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get update
  - wget https://github.com/OSGeo/proj/releases/download/6.2.1/proj-6.2.1.tar.gz
  - tar -xzvf proj-6.2.1.tar.gz
  - pushd proj-6.2.1 && ./configure --prefix=/usr && make && sudo make install && popd
