language: rust

dist: xenial

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
env:
  global:
    - INSTALL_PROJ_FIRST=1 _PROJ_SYS_TEST_EXPECT_BUILD_FROM_SRC=0

# test both features on Linux stable, but only pkg_config on macOS stable
jobs:
  include:
    - os: linux
      env: INSTALL_PROJ_FIRST=0 _PROJ_SYS_TEST_EXPECT_BUILD_FROM_SRC=1
    - os: osx
      env: INSTALL_PROJ_FIRST=0 _PROJ_SYS_TEST_EXPECT_BUILD_FROM_SRC=1
    # verify we can build from src even if its already installed
    - os: linux
      env: INSTALL_PROJ_FIRST=1 PROJ_FEATURES="--features bundled_proj" _PROJ_SYS_TEST_EXPECT_BUILD_FROM_SRC=1
    - os: osx
      env: INSTALL_PROJ_FIRST=1 PROJ_FEATURES="--features bundled_proj" _PROJ_SYS_TEST_EXPECT_BUILD_FROM_SRC=1

before_install:
  - |
    if [[ $INSTALL_PROJ_FIRST == "1" ]]; then
      case $TRAVIS_OS_NAME in
      "linux")
        sudo apt-get update
        sudo apt-get -y install pkg-config
        wget https://download.osgeo.org/proj/proj-7.1.0.tar.gz
        tar -xzvf proj-7.1.0.tar.gz
        pushd proj-7.1.0 && ./configure --prefix=/usr && make && sudo make install && popd
        ;;
      "osx")
        brew update
        brew upgrade pkg-config
        brew upgrade proj
        ;;
      esac
    fi

script:
  - cargo test $PROJ_FEATURES

after_failure:
  - ls /home/travis/build/georust/proj-sys/PROJSRC/
  - ls /home/travis/build/georust/proj-sys/PROJSRC/proj

cache: cargo
