[package]
name = "proj"
description = "Rust bindings for PROJ.4"
version = "0.6.0"
authors = [
  "Corey Farwell <coreyf@rwell.org>",
  "Alex Morega <alex@grep.ro>",
  "Stephan Hügel <urschrei@gmail.com>"
]
repository = "https://github.com/georust/proj"
keywords = ["proj", "projection", "osgeo", "geo"]
license = "MIT/Apache-2.0"

[dependencies]
proj-sys = "0.7.0"
geo-types ="0.2"
libc = "0.2.39"
num-traits = "0.2"
failure = "0.1.2"
