[package]
name = "proj"
description = "Rust bindings for PROJ"
version = "0.11.0"
authors = [
  "Corey Farwell <coreyf@rwell.org>",
  "Alex Morega <alex@grep.ro>",
  "Stephan Hügel <urschrei@gmail.com>"
]
repository = "https://github.com/georust/proj"
keywords = ["proj", "projection", "osgeo", "geo"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
proj-sys = "0.11.2"
geo-types ="0.4.3"
libc = "0.2.62"
num-traits = "0.2.8"
thiserror = "1.0.4"

[dev-dependencies]
assert_approx_eq = "1.1.0"

[package.metadata.docs.rs]
features = [ "proj-sys/docs-rs" ] # This feature will be enabled during the docs.rs build
